FROM nodered/node-red:latest

RUN cd /data && npm install node-red-contrib-influxdb

COPY --chown=node-red:node-red nodered/flows.json /data/flows.json
COPY --chown=node-red:node-red nodered/flows_cred.json /data/flows_cred.json
COPY --chown=node-red:node-red nodered/settings.js /data/settings.js
